# CSC 422: Machine and Deep Learning - Jekyll Configuration
title: "CSC 422: Machine and Deep Learning"
description: "Unlock the Power of AI and Transform Data into Intelligence"
# For project pages use your username site + repo baseurl
# Example: https://USERNAME.github.io and baseurl: /REPO_NAME
baseurl: "/CBU-CSC422"
url: "https://robbyswimmer.github.io"

# Course Information
course:
  number: "CSC 422"
  name: "Machine and Deep Learning"
  semester: "Fall 2025"
  university: "California Baptist University"
  
# Instructor Information
instructor:
  name: "Professor Robert Moseley, MS"
  email: "rmoseley@calbaptist.edu"
  office: "EGR333"
  phone: "(951) 552–8851"
  office_hours: "Monday/Wednesday 10:30am-12:00pm, 1:00pm–3:00pm"
  image: "/Materials/Art/professor.png"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-seo-tag

# Collections
collections:
  assignments:
    output: true
    permalink: /:collection/:name/

# Exclude files
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - add_to_readme.md

# Site navigation
navigation:
  - name: "Home"
    url: "/"
  - name: "Assignments"
    url: "/assignments/"
  - name: "Syllabus"
    url: "/syllabus/"
  - name: "Resources"
    url: "/resources/"

# Course phases
phases:
  - name: "Foundation Building"
    weeks: "1-3"
    color: "#FFE6E6"
    description: "Build Your ML Foundation"
  - name: "Advanced Techniques"  
    weeks: "4-6"
    color: "#E6F3FF"
    description: "Level Up Your Skills"
  - name: "Deep Learning Revolution"
    weeks: "7-9" 
    color: "#E6FFE6"
    description: "Master Advanced Neural Networks"
  - name: "AI Mastery & Innovation"
    weeks: "10-14"
    color: "#FFF0E6" 
    description: "Become an AI Expert"

# Default front matter
defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"