# Jekyll Configuration for CSC 422 Course Site
title: "CSC 422: Machine and Deep Learning"
description: "Unlock the Power of AI and Transform Data into Intelligence"
baseurl: "/CBU-CSC422"
url: "https://robbyswimmer.github.io/CBU-CSC422"

# Course Information
course:
  number: "CSC 422"
  name: "Machine and Deep Learning"
  semester: "Fall 2025"
  university: "California Baptist University"

# Instructor Information
instructor:
  name: "Professor Robert Moseley, MS"
  email: "rmoseley@calbaptist.edu"
  office: "EGR333"
  phone: "(951) 552–8851"
  office_hours: "Monday/Wednesday 10:30am-12:00pm, 1:00pm–3:00pm"
  image: "/Materials/Art/professor.png"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
